// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuotingEngine.Infrastructure.Data;

#nullable disable

namespace QuotingEngine.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260919063450_SeedBullionCatalog")]
    partial class SeedBullionCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuotingEngine.Core.Models.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DefaultMarginPercentage")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("GrossWeightGrams")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PurityPercentage")
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CatalogItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DefaultMarginPercentage = 0.03m,
                            GrossWeightGrams = 33.930m,
                            Name = "1 oz South African Krugerrand",
                            PurityPercentage = 0.9167m,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            DefaultMarginPercentage = 0.04m,
                            GrossWeightGrams = 33.931m,
                            Name = "1 oz US Mint Gold Eagle",
                            PurityPercentage = 0.9167m,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            DefaultMarginPercentage = 0.03m,
                            GrossWeightGrams = 31.1035m,
                            Name = "1 oz Canadian Maple Leaf",
                            PurityPercentage = 0.9999m,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            DefaultMarginPercentage = 0.025m,
                            GrossWeightGrams = 31.1035m,
                            Name = "1 oz Australian Kangaroo (Perth Mint)",
                            PurityPercentage = 0.9999m,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            DefaultMarginPercentage = 0.02m,
                            GrossWeightGrams = 31.1035m,
                            Name = "1 oz ABC Bullion Cast Bar",
                            PurityPercentage = 0.9999m,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            DefaultMarginPercentage = 0.03m,
                            GrossWeightGrams = 31.1035m,
                            Name = "1 oz PAMP Suisse Fortuna Bar",
                            PurityPercentage = 0.9999m,
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            DefaultMarginPercentage = -0.15m,
                            GrossWeightGrams = 0m,
                            Name = "Generic Scrap 9k",
                            PurityPercentage = 0.375m,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            DefaultMarginPercentage = -0.10m,
                            GrossWeightGrams = 0m,
                            Name = "Generic Scrap 14k",
                            PurityPercentage = 0.585m,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            DefaultMarginPercentage = -0.08m,
                            GrossWeightGrams = 0m,
                            Name = "Generic Scrap 18k",
                            PurityPercentage = 0.750m,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            DefaultMarginPercentage = -0.05m,
                            GrossWeightGrams = 0m,
                            Name = "Generic Scrap 22k",
                            PurityPercentage = 0.916m,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            DefaultMarginPercentage = -0.05m,
                            GrossWeightGrams = 0m,
                            Name = "Generic Scrap 24k",
                            PurityPercentage = 0.999m,
                            Type = 0
                        });
                });

            modelBuilder.Entity("QuotingEngine.Core.Models.LineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DealerMarginPercentage")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("DefaultPremiumPct")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GrossWeightGrams")
                        .HasColumnType("numeric(18,6)");

                    b.Property<byte[]>("ItemPhoto")
                        .HasColumnType("bytea");

                    b.Property<decimal>("LiveSpotPricePerGram")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ManagerOverrideSpreadDollar")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PurityPercentage")
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("StoredSpotPriceG")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("LineItems");
                });

            modelBuilder.Entity("QuotingEngine.Core.Models.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerIdDocument")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerIdNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GracePeriodHours")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LockedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("LockedSpotPricePerGram")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("PdfSha256Hash")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("QuotingEngine.Core.Models.LineItem", b =>
                {
                    b.HasOne("QuotingEngine.Core.Models.Quote", null)
                        .WithMany("Items")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("QuotingEngine.Core.Models.Quote", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
